spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lsh_board_db
    username: root
    password: zerobase
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  swagger-ui:
    path: /api-doc.html
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true